### ISSUE TITLE
Need documentation on how to run unit tests and use the API

### ISSUE THREAD

**Issue by bbala-github** [Pivotal-Data-Attic/pivotalrd-libhdfs3#1]
Hi,

I was looking for a native solution to read data from HDFS and stumbled upon this project. It is great to find a native client for HDFS.

I tried to clone the repo and build it locally, the code compiles but I am facing issues with running unit tests and also to get a file downloaded from our existing HDFS setup.

Need documentation help to get started on this. Please let me know where can I find some help on the same.

Thanks.

**Comment by rhl-** [comment]
@bbala-github  can you post your specific problem? i've been able to get the project compiling and running just fine, and I can offer help.

**Comment by kdunn-pivotal** [comment]
Vote to close this issue unless @bbala-github says otherwise.
