### ISSUE TITLE
Use libhdfs3 concurrently from multiple processes

### ISSUE THREAD

**Issue by mrocklin** [Pivotal-Data-Attic/pivotalrd-libhdfs3#25]
When using libhdfs3 concurrently from multiple processes on the same machine I sometimes get errors like the following:

```
2016-01-19 22:12:17.158248, p4535, th139888459806528, INFO Retry idempotent RPC call "getFsStats" on server "localhost:8020"
2016-01-19 22:12:17.227239, p4536, th139888459806528, ERROR Failed to invoke RPC call "getFsStats" on server "localhost:8020": 
RpcChannel.cpp: 413: HdfsRpcException: Failed to invoke RPC call "getFsStats" on server "localhost:8020"
    @    Hdfs::Internal::RpcChannelImpl::invokeInternal(std::shared_ptr<Hdfs::Internal::RpcRemoteCall>)
    @    Hdfs::Internal::RpcChannelImpl::invoke(Hdfs::Internal::RpcCall const&)
```

    [libprotobuf ERROR google/protobuf/message_lite.cc:123] Can't parse message of type "Hdfs.Internal.RpcResponseHeaderProto" because it is missing required fields: callId, status

```
2016-01-19 22:33:04.478387, p1636, th140167991510784, ERROR Failed to invoke RPC call "getBlockLocations" on server "localhost:8020": 
RpcChannel.cpp: 780: HdfsRpcException: RPC channel to "localhost:8020" got protocol mismatch: RPC channel cannot parse response header.
```

Is this a known problem?  Am I misusing `libhdfs3` in some way?  Everything works very well when using this library from a single process.

**Comment by wangzw** [comment]
We are using libhdfs3 both in multiple processes and multiple threads applications. It suppose to work well.

Which version of HDFS do you use? It seems a protocol mismatch issue. And there is another possible reason which can cause this error, that is your HDFS is not running on "localhost:8020", but some other application does, can you verify that with `netstat` command?

**Comment by mrocklin** [comment]
Have you tried using libhdfs3 in multiple forked processes?  My issue arises when I create a connection to HDFS in one process, then fork many child processes and create other new connections within them.

HDFS is definitely running on 8020 on my development cluster.  Everything works well most of the time.

**Comment by wangzw** [comment]
I did not test this case. libhdfs3 will create some threads and set some global variables at the first time of creating a connection. Fork after setup a connection may get trouble.

**Comment by spothineni** [comment]
I am trying to read thousands of files from hdfs, do we need to make just one connection with hdfsBuilderConnect and reuse it though out application? or is that ok to make connection per every file and close it?

**Comment by wangzw** [comment]
@spothineni one connection is enough.
