### ISSUE TITLE
Using libhdfs3 with CDH 5.7.0 (beta) parse file permission fail

### ISSUE THREAD

**Issue by ayang008** [Pivotal-Data-Attic/pivotalrd-libhdfs3#31]
The error message is: cannot convert 8685 to "Permission"
It seems like there are more bits than expected. It is '20755', I don't know where does the '2' come from.
Directories' permission are fine.

**Comment by ayang008** [comment]
I commented out the check codes in Permission::Permission, it worked.
Then I found another problem:
libhdfs3 doesn't have the decrypt code for following hdfs feature:
http://www.cloudera.com/documentation/enterprise/latest/topics/cdh_sg_hdfs_encryption.html
So reading files from an encrypted zone (directory) will get encrypted content which should be decrypted by libhdfs3.

**Comment by changleicn** [comment]
yes, it is a feature not implemented yet. it is in the roadmap. this repo has been moved to apache hawq code base. if you have other requests, please go to apache hawq github, mailing list and jira. thanks!
https://cwiki.apache.org/confluence/display/HAWQ/Contributing+to+HAWQ

**Comment by ayang008** [comment]
changeleicn,
thanks for your reply.

**Comment by kdunn-pivotal** [comment]
Vote to close this issue.
