### ISSUE TITLE
Compile libhdfs3 failed due to error in source code

### ISSUE THREAD

**Issue by daniel94104** [Pivotal-Data-Attic/pivotalrd-libhdfs3#34]
> In file included from /data/dw_hbkas_home/qgzheng/pivotalrd-libhdfs3-2.2.31/src/client/Pipeline.h:37,
                 from /data/dw_hbkas_home/qgzheng/pivotalrd-libhdfs3-2.2.31/src/client/OutputStreamImpl.h:40,
                 from /data/dw_hbkas_home/qgzheng/pivotalrd-libhdfs3-2.2.31/src/client/FileSystemImpl.cpp:40:
/data/dw_hbkas_home/qgzheng/pivotalrd-libhdfs3-2.2.31/src/client/PipelineAck.h: In member function ‘bool Hdfs::Internal::PipelineAck::isSuccess()’:
/data/dw_hbkas_home/qgzheng/pivotalrd-libhdfs3-2.2.31/src/client/PipelineAck.h:67: error: ‘Status’ is not a class or namespace

This is error message. 

```javascript
 63     bool isSuccess() {
 64         int size = proto.status_size();
 65 
 66         for (int i = 0; i < size; ++i) {
 67             if (Status::DT_PROTO_SUCCESS != proto.status(i)) {
 68                 return false;
 69             }
```

Here is the code I found where the error occurred.

**Comment by wangzw** [comment]
Your compiler do not support C++11 or you did not enable c++11 feature.

**Comment by daniel94104** [comment]
got it. 
Thanks!
