### ISSUE TITLE
Need a version compatible with SUSE 11 SP3

### ISSUE THREAD

**Issue by daniel94104** [Pivotal-Data-Attic/pivotalrd-libhdfs3#35]
Since SUSE 11 only has a GCC with 4.3.4, it cannot compile newer version of libhdfs3.  I wonder that whether you could provide a version compatible with SUSE 11. 

Thanks

**Comment by wangzw** [comment]
libhdfs3 depends on many c++ 11 features. It easier to upgrade you gcc to a version which support c++ 11 than change libhdfs3 code to work with outdated compiler.

We tested libhdfs3 with gcc 4.4.2 and boost. If you do not want to use boost, you have to use gcc 4.7 or newer.

**Comment by daniel94104** [comment]
It would cost too much to upgrade our SUSE system since we are a large company. Is there any earlier version could compatible with SUSE 11? Does it have any bugs in it? 

Thanks

**Comment by wangzw** [comment]
libhdfs3 was designed to work with c++ 11 features. There is no such earlier version to work with gcc 4.3.

**Comment by daniel94104** [comment]
ok, thanks
